pub mod borrow;
mod encoding;
mod lattice;
mod liveness;
mod mir;
pub mod mir_variable_grouping;
pub mod offset_sign;
pub(crate) mod output_params;
pub mod ownership;
pub mod struct_array_field;
pub mod type_qualifier;
