pub mod aliasing;
pub mod array_local_provenance;
pub mod borrow;
mod encoding;
pub mod fn_ptr_groups;
pub mod fn_ptr_rewrite_decision;
mod lattice;
mod liveness;
pub mod loop_summary;
mod mir;
pub mod mir_variable_grouping;
pub mod nullity;
pub mod offset_sign;
pub(crate) mod output_params;
pub mod ownership;
pub mod pointer_flow;
pub mod read_extent;
pub mod struct_array_field;
pub mod struct_copy;
pub mod struct_param_field_spec;
pub mod type_qualifier;
